apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: sample-vpc2
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    enableDnsHostNames: false
    enableDnsSupport: true
    instanceTenancy: default
    region: us-east-1